apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: helloworld
spec:
  containers:
  - name: ngnix
    image: merpso/ngnix-plus-k8s-ingress
  - name: k8s-demo
    image: arjunachari12/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 80
